package wedbot.fakes

import wedbot.domain.repository.TextRepository

class FakeTextRepository : TextRepository {
    override fun internalError(): String = "internalError"
    override fun totalSleeve(): String = "totalSleeve"
    override fun generateGreeting(name: String?): String = "generateGreeting"
    override fun infoMessage(): String = "infoMessage"
    override fun helpMessage(): String = "helpMessage"
    override fun shareContactError(): String = "shareContactError"
    override fun shareContactLabel(): String = "shareContactLabel"
    override fun userNotFound(): String = "userNotFound"
    override fun weakRights(): String = "weakRights"
    override fun alreadyRegistered(): String = "alreadyRegistered"
    override fun eventStatusPingFirst(): String = "eventStatusPingFirst"
    override fun eventStatusPingDaily(name: String?): String = "eventStatusPingDaily"
    override fun eventStatusAcceptButton(): String = "eventStatusAcceptButton"
    override fun eventStatusRejectButton(): String = "eventStatusRejectButton"
    override fun eventStatusThinkButton(): String = "eventStatusThinkButton"
    override fun eventStatusAccepted(): String = "eventStatusAccepted"
    override fun eventStatusRejected(): String = "eventStatusRejected"
    override fun eventStatusThinkAgain(): String = "eventStatusThinkAgain"
    override fun menuMessage(): String = "menuMessage"
    override fun menuUpdated(): String = "menuUpdated"
    override fun calendarMessage(): String = "calendarMessage"
    override fun adminPingStarted(): String = "adminPingStarted"
    override fun adminPingAllPrompt(): String = "adminPingAllPrompt"
    override fun adminPingAllButton(): String = "adminPingAllButton"
    override fun adminPingGuestsPrompt(): String = "adminPingGuestsPrompt"
    override fun adminPingGuestsButton(): String = "adminPingGuestsButton"
    override fun adminPingCancel(): String = "adminPingCancel"
    override fun adminPingCancelButton(): String = "adminPingCancelButton"
    override fun adminPingSucceed(): String = "adminPingSucceed"
    override fun adminMessageHeader(): String = "adminMessageHeader"
    override fun menuButtonInfo(): String = "menuButtonInfo"
    override fun menuButtonIcs(): String = "menuButtonIcs"
    override fun menuButtonLocation(): String = "menuButtonLocation"
    override fun menuButtonEventStatus(): String = "menuButtonEventStatus"
    override fun menuButtonHelp(): String = "menuButtonHelp"
    override fun menuButtonStatusTable(): String = "menuButtonStatusTable"
    override fun menuButtonPingGuests(): String = "menuButtonPingGuests"
    override fun menuButtonDressCode(): String = "menuButtonDressCode"
    override fun techWorks(): String = "techWorks"
}
